# Generated by Django 3.1.7 on 2021-03-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='realtor',
        ),
    ]
