# Generated by Django 3.1.7 on 2021-03-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210309_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deposit_down',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
