# Generated by Django 3.1.7 on 2021-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20210309_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='doorman',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='laundry',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='pets_allowed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='storage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='valet',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
