# Generated by Django 3.1.7 on 2021-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20210310_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='sqft',
        ),
        migrations.AddField(
            model_name='room',
            name='bedroom_sqft',
            field=models.CharField(default='10x12', max_length=20),
            preserve_default=False,
        ),
    ]
