# Generated by Django 3.1.7 on 2021-03-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_auto_20210311_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lat',
            field=models.DecimalField(decimal_places=6, default='0', help_text='Go to https://www.google.com/maps and search your apartments address. Right-click on the pointer and copy your lat and lng values', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='lng',
            field=models.DecimalField(decimal_places=6, default='0', help_text='Go to https://www.google.com/maps and search your apartments address. Right-click on the pointer and copy your lat and lng values', max_digits=9),
            preserve_default=False,
        ),
    ]
