# Generated by Django 3.1.7 on 2021-03-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20210309_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='doorman',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='laundry',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='pets_allowed',
            field=models.CharField(max_length=20),
        ),
    ]
