# Generated by Django 3.1.7 on 2021-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_auto_20210310_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lat',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='lng',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=25),
            preserve_default=False,
        ),
    ]
