# Generated by Django 3.1.7 on 2021-03-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20210322_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lng',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
