# Generated by Django 3.1.7 on 2021-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_auto_20210322_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
